Changes to yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -45,7 +45,14 @@ jobs:
 
             - name: Terraform Initialize
               run: |
-                terraform init
+                if [ "${{github.event.inputs.environment}}"=="dev"]; then
+                    terraform init -backend-config=backend-dev.tf
+                elif [ "${{github.event.inputs.environment}}"=="prod"]; then
+                    terraform init -backend-config=backend-prod.tf
+                else
+                    echo "Invalid ENV"
+                    exit 1
+                fi
             - name: Terraform Choose Workspace
               run: |
                 terraform workspace list | grep -q "${{ github.event.inputs.environment }}" \
diff --git a/.github/workflows/destroy.yml b/.github/workflows/destroy.yml
--- a/.github/workflows/destroy.yml
+++ b/.github/workflows/destroy.yml
@@ -37,8 +37,17 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ap-south-1
 
-      - name: Terraform Init
-        run: terraform init
+     
+      - name: Terraform Initialize
+        run: |
+                if [ "${{github.event.inputs.environment}}"=="dev"]; then
+                    terraform init -backend-config=backend-dev.tf
+                elif [ "${{github.event.inputs.environment}}"=="prod"]; then
+                    terraform init -backend-config=backend-prod.tf
+                else
+                    echo "Invalid ENV"
+                    exit 1
+                fi
 
       - name: Select Workspace
         run: terraform workspace select ${{ github.event.inputs.environment }}
